---
- name: Deploy App
  hosts: app
  tasks:
    - name: Install git
      become: yes
      package:
        name:
          - git
          - bundler
        state: present
        update_cache: yes

    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/ubuntu/reddit
        version: monolith
      notify: reload puma

    - name: Bundle install
      bundler:
        state: present
        chdir: /home/ubuntu/reddit

    - name: enable puma
      become: yes
      systemd:
        name: puma
        enabled: yes

  handlers:
      - name: reload puma
        become: yes
        systemd:
          name: puma
          state: restarted
