---
- name: install ruby
  hosts: all
  become: true
  tasks:
    - name: install ruby
      package:
        name:
          - ruby-full
          - ruby-bundler
          - build-essential
        update_cache: yes
        state: present
